version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: presence
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/presence
      TENANT_ID: ${TENANT_ID}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  db_data:
