# Generated by Django 5.2.5 on 2025-08-27 19:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aad_user_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('display_name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PresenceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('AvailableIdle', 'AvailableIdle'), ('Away', 'Away'), ('BeRightBack', 'BeRightBack'), ('Busy', 'Busy'), ('BusyIdle', 'BusyIdle'), ('DoNotDisturb', 'DoNotDisturb'), ('Offline', 'Offline'), ('PresenceUnknown', 'PresenceUnknown')], max_length=32)),
                ('activity', models.CharField(choices=[('Available', 'Available'), ('Away', 'Away'), ('BeRightBack', 'BeRightBack'), ('Busy', 'Busy'), ('DoNotDisturb', 'DoNotDisturb'), ('InACall', 'In a call'), ('InAConferenceCall', 'In a conference call'), ('InAMeeting', 'In a meeting'), ('OffWork', 'Off work'), ('Offline', 'Offline'), ('OutOfOffice', 'Out of office'), ('Presenting', 'Presenting'), ('UrgentInterruptionsOnly', 'Urgent interruptions only'), ('OnThePhone', 'On the phone'), ('PresenceUnknown', 'Presence unknown')], max_length=32)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_snapshots', to='teamspresenceapp.tenantuser')),
            ],
            options={
                'ordering': ['-fetched_at', 'user_id'],
                'get_latest_by': 'fetched_at',
                'indexes': [models.Index(fields=['user', 'fetched_at'], name='teamspresen_user_id_0d4d8f_idx'), models.Index(fields=['fetched_at'], name='teamspresen_fetched_fcb1a9_idx'), models.Index(fields=['availability'], name='teamspresen_availab_33e24d_idx'), models.Index(fields=['activity'], name='teamspresen_activit_79673f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PresenceCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('AvailableIdle', 'AvailableIdle'), ('Away', 'Away'), ('BeRightBack', 'BeRightBack'), ('Busy', 'Busy'), ('BusyIdle', 'BusyIdle'), ('DoNotDisturb', 'DoNotDisturb'), ('Offline', 'Offline'), ('PresenceUnknown', 'PresenceUnknown')], db_index=True, max_length=32)),
                ('activity', models.CharField(choices=[('Available', 'Available'), ('Away', 'Away'), ('BeRightBack', 'BeRightBack'), ('Busy', 'Busy'), ('DoNotDisturb', 'DoNotDisturb'), ('InACall', 'In a call'), ('InAConferenceCall', 'In a conference call'), ('InAMeeting', 'In a meeting'), ('OffWork', 'Off work'), ('Offline', 'Offline'), ('OutOfOffice', 'Out of office'), ('Presenting', 'Presenting'), ('UrgentInterruptionsOnly', 'Urgent interruptions only'), ('OnThePhone', 'On the phone'), ('PresenceUnknown', 'Presence unknown')], db_index=True, max_length=32)),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_presence', to='teamspresenceapp.tenantuser')),
            ],
            options={
                'indexes': [models.Index(fields=['availability'], name='teamspresen_availab_214d8e_idx'), models.Index(fields=['activity'], name='teamspresen_activit_37eb43_idx'), models.Index(fields=['fetched_at'], name='teamspresen_fetched_14ad69_idx')],
            },
        ),
    ]
